services:
  - type: web
    name: spotify-vote-queue
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 1 -b 0.0.0.0:$PORT
    envVars:
      - key: RENDER
        value: "1"
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false